AUGMENTATION_MAX_ANGLE = 1.0  # radian
GAUSSIAN_SIGMA = 1.
GAUSSIAN_LAPLACIAN_K_SIZE = 7
MODEL_TYPE_UNET = 'unet'
MODEL_TYPE_DCT = 'dct'
MODEL_TYPE_PERCEPTUAL = 'perceptual'
LOW_DOSE = 'Low dose images'
FULL_DOSE = 'Full dose images'

LOW_DOSE_FOLDER = 'LowDose'
HIGH_DOSE_FOLDER = 'HighDose'
CHKPOINT_NAME = 'cp.ckpt'

# head constants
HEAD_MAX_HU = 3985.
HEAD_DETECTOR_PIXEL_SIZE = 1.25

# chest constants
CHEST_MAX_HU = 4238.
CHEST_DETECTOR_PIXEL_SIZE = 1.25